[general]
live-config = 1
framerate = 120
autosens = 0 # increase to make sensitivity increase even faster.
sensitivity = 9000
bars = 0 # 0(auto) - 512
bar_width = 1
bar_spacing = 1
center_align = 1 # center bars in terminal, if there is space.
max_height = 100 # % of terminal height
lower_cutoff_freq = 44 #65.41 is the start of the second octave # Note: there is a minimum total bandwidth of 43Mhz x number of bars.
higher_cutoff_freq = 8000 # 7982.16 is the end of the eigth octave, cava will increase automatically if needed
sleep_timer = 0 # 0 = disable

[input]
method = pipewire
source = pc-audio-sink.monitor
sample_rate = 48000
sample_bits = 32
channels = 1
active = 1 # Force the node to always process.
remix = 1 # remix: Allow pipewire to remix audio channels to match cava's channel count for surround sound.
virtual = 1 # virtual: Set the node to virtual, to avoid recording notifications from the DE.

[output]
method = noncurses # noncursesto only print changes from frame to frame in the terminal.
# Orientation of the visualization. Can be 'bottom', 'top', 'left', 'right' or 'horizontal'. Default is 'bottom'. 'left and 'right' are only supported on ncurses output. 'horizontal' (bars go up and down from center) is only supported on noncurses output.
orientation = bottom
channels = mono
mono_option = average
reverse = 0
xaxis = none

# enable synchronized sync. 1 = on, 0 = off removes flickering in alacritty terminal emulator.
synchronized_sync = 0 # crashed once maybe this at 1 was responible
disable_blanking = 0
show_idle_bar_heads = 0
waveform = 0

[color]
background = '#000000'
foreground = '#33ffff'

gradient = 1
 gradient_color_1 = '#59cc33'
 gradient_color_2 = '#80cc33'
 gradient_color_3 = '#a6cc33'
 gradient_color_4 = '#cccc33'
 gradient_color_5 = '#cca633'
 gradient_color_6 = '#cc8033'
 gradient_color_7 = '#cc5933'
 gradient_color_8 = '#ff0000'
horizontal_gradient = 1
 horizontal_gradient_color_1 = '#c45161'
 horizontal_gradient_color_2 = '#e094a0'
 horizontal_gradient_color_3 = '#f2b6c0'
 horizontal_gradient_color_4 = '#f2dde1'
 horizontal_gradient_color_5 = '#cbc7d8'
 horizontal_gradient_color_6 = '#8db7d2'
 horizontal_gradient_color_7 = '#5e62a9'
 horizontal_gradient_color_8 = '#434279'

# If both vertical and horizontal gradients are enabled, the vertical one will be blended in this direction.
# Can be 'up', 'down', 'left' or 'right'. 'up' means the vertical gradient will be blended in from bottom to top. I.e. the bottom will only be the horizontal and top will only be the vertical color of the gradient.
; blend_direction = 'up'

; theme = 'none'


[smoothing]
; monstercat = 0
; waves = 0
# 100 will be very slow and smooth, 0 will be fast but noisy.
noise_reduction = 77


[eq]
#You can have as many keys as you want. min 2 or 0, More keys = more precision.
; 1 = 1 # bass
; 2 = 1
; 3 = 1 # midtone
; 4 = 1
; 5 = 1 # treble
