[general]
live-config = 1
framerate = 120
autosens = 0 # increase to make sensitivity increase even faster.
sensitivity = 5000
bars = 0 # 0(auto) - 512
bar_width = 1
bar_spacing = 1
center_align = 1 # center bars in terminal, if there is space.
max_height = 100 # % of terminal height
lower_cutoff_freq = 180 #65.41 is the start of the second octave # Note: there is a minimum total bandwidth of 43Mhz x number of bars.
higher_cutoff_freq = 9000 # 7982.16 is the end of the eigth octave, cava will increase automatically if needed
sleep_timer = 0 # 0 = disable

[input]
method = pipewire
source = "scarlett-mic-playback"
sample_rate = 48000
sample_bits = 128
channels = 1
active = 1 # Force the node to always process.
remix = 1 # remix: Allow pipewire to remix audio channels to match cava's channel count for surround sound.
virtual = 0 # virtual: Set the node to virtual, to avoid recording notifications from the DE.

[output]
method = noncurses # noncursesto only print changes from frame to frame in the terminal.
orientation = horizontal
channels = mono
mono_option = right
reverse = 0
horizontal_stereo = 1
left_bottom = 1
xaxis = none
synchronized_sync = 0 # crashed once maybe this at 1 was responible
disable_blanking = 0
show_idle_bar_heads = 1
# show waveform instead of frequency spectrum, 1 = on, 0 = off
waveform = 0

[color]
background = '#000000'
foreground = '#33ffff'

gradient = 1
 gradient_color_1 = '#59cc33'
 gradient_color_2 = '#80cc33'
 gradient_color_3 = '#a6cc33'
 gradient_color_4 = '#cccc33'
 gradient_color_5 = '#cca633'
 gradient_color_6 = '#cc8033'
 gradient_color_7 = '#cc5933'
 gradient_color_8 = '#ff0000'

horizontal_gradient = 1
 horizontal_gradient_color_1 = '#c45161'
 horizontal_gradient_color_2 = '#e094a0'
 horizontal_gradient_color_3 = '#f2b6c0'
 horizontal_gradient_color_4 = '#f2dde1'
 horizontal_gradient_color_5 = '#cbc7d8'
 horizontal_gradient_color_6 = '#8db7d2'
 horizontal_gradient_color_7 = '#5e62a9'
 horizontal_gradient_color_8 = '#434279'
blend_direction = 'down'
; theme = 'none'

[smoothing]
monstercat = 0
waves = 0
noise_reduction = 0


[eq]
; 1 = 1 # bass
; 2 = 1
; 3 = 1 # midtone
; 4 = 1
; 5 = 1 # treble
