

# UWSM is setup to handle the following services so they dont need to be set here
       # systemctl --user enable --now hypridle.service
       # systemctl --user enable --now hyprsunset.service
       # dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP 

exec-once = uwsm finalize FINALIZED="Done UWSM finalizing"  # Needed for uwsm
exec-once = tmux setenv -g HYPRLAND_INSTANCE_SIGNATURE $HYPRLAND_INSTANCE_SIGNATURE # needed for tmux
exec-once = tmux new-session -d -s mainctl                  # Session for my main tty
exec-once = tmux new-session -d -s clipboard                # Session for clipboard and paste shortcuts
exec-once = app2unit udiskie                                # Auto Mount drives
exec-once = wl-paste --type text --watch cliphist store &   # needed for clipboard
exec-once = wl-paste --type image --watch cliphist store &  # needed for clipboard
exec-once = rm "$HOME/.cache/cliphist/db"                   # delete history at every restart
#exec-once = #loginctl lock-session                         # immediately lock session after launch
#exec-once = ags run ~/.config/ags/mybar.tsx &
#exec-once = app2unit openrgb --noautoconnect --loglevel 0 &
