# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace
# halign: left, center, right, none. valign: top, center, bottom, none
# Vars 
#    $USER - username (e.g. linux-user)
#    $DESC - user description (e.g. Linux User)
    #$TIME - current time in 24-hour format (e.g. 13:37)
    #$TIME12 - current time in 12-hour format (e.g. 1:37 PM)
    #$LAYOUT - current keyboard layout
    #$ATTEMPTS - failed authentication attempts
    #$FAIL - last authentication fail reason
    #$PAMPROMPT - pam auth last prompt
    #$PAMFAIL - pam auth last fail reason
    #$FPRINTPROMPT - fingerprint auth last prompt
    #$FPRINTFAIL - fingerprint auth last fail reason

general {
    hide_cursor = 1
    ignore_empty_input = 1
    immediate_render = 1 #makes hyprlock immediately start to draw widgets. Backgrounds will render background:color until their background:path resource is available
    text_trim = 1 #sets if the text should be trimmed, useful to avoid trailing newline in commands output
    fractional_scaling = 0 #  0 - disabled, 1 - enabled, 2 - auto (2 is default)
    screencopy_mode 0 # 0 - gpu accelerated, 1 - cpu based (slow)
    fail_timeout = 1000 # milliseconds until the ui resets after a failed auth attempt
}

animations {
    #fadeIn fadeout inputFieldColors inputFieldFade inputFieldWidth inputFieldDots
    enabled = 1
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor = # empty = all monitors
    color = rgba(0,0,0,0)
    path = screenshot
    blur_passes = 3
}

auth {
    pam {
    enabled = 1 # enable pam authentication
    module = hyprlock # If the module isn’t found in /etc/pam.d, “su” will be used as a fallback
    }
    fingerprint {
    enabled = 0 
    ready_message = "Finger"
    present_message = "mhm yes" # msg while scanning
    retry_delay = 250 # delay in ms after an unrecognized finger is scanned before another finger can be scanned.
    }
}

input-field {
    monitor = # empty = all monitors
    size = 13%, 20%
    outline_thickness = 20
    inner_color = rgba(0, 0, 0, 0) # no fill
    outer_color = rgba(33ccffee) rgba(00ff99ee) 45deg
    check_color = rgba(0000ffee)
    fail_color = rgba(ff0000ee)
    font_color = rgba(ffffffff)
    fade_on_empty = false
    rounding = 100%
    placeholder_text = #󰌾 
    fail_text = Nope
    hide_input = true
    #dots_size = 0.1
    #dots_spacing = 0.1
    position = 0, 0
    halign = center
    valign = center
}

# DATE
label {
    monitor = # empty = all monitors
    text = $TIME
    font_size = 25
    position = 0%, -5%
    halign = center
    valign = center
}
label {
    monitor = # empty = all monitors
    text = cmd[update:60000] date +"%A," # Weekday update every 60 seconds
    font_size = 25
    position = 0%, 5%
    halign = center
    valign = center
}
label {
    monitor = # empty = all monitors
    text = cmd[update:60000] date +"%d %B %Y" # Date update every 60 seconds
    font_size = 25
    position = 0%, 0%
    halign = center
    valign = center
}
