max-gamma = 100 # abs max is 200

profile {
    time = 21:00
    temperature = 5000
    gamma = 0.8 # default is 1
    identity = 0 # if 1 only gamma is adjusted not temperature
    }
profile {
    time = 06:00
    temperature = 6000
    gamma = 1.0
    identity = 0 # if 1 only gamma is adjusted not temperature
    }
