splash = false
splash_offset = 2 # percentage height of splash message
splash_color = 55ffffff
ipc = on
# Laptopscreen
preload = ~/Pictures/sunset.jpg
wallpaper = desc:Thermotrex Corporation TL134ADXP01-0, ~/Pictures/sunset.jpg

# asus oled
#preload = ~/Pictures/sunset.jpg
#wallpaper = desc:Thermotrex Corporation TL134ADXP01-0, ~/Pictures/sunset.jpg

unload = unused # removes preloaded items from memory
