# Main Desk screen
monitorv2 {
    output = desc:BNQ ZOWIE XL LCD EBW9N00747SL0
    mode = 1920x1080@360
    position = 640x-1080
    scale = 1
    bitdepth = 10
    cm = hdr #hdredid
    vrr = 0 # 0 - off, 1 - on, 2 - fullscreen only
    supports_wide_color = 1
    supports_hdr = 1
    #sdrbrightness = 1.2
    #sdrsaturation = 0.98
    #sdr_min_luminance = 0.005
    #sdr_max_luminance = 160
    #min_luminance = 0.005
    #max_luminance = 400
}
# Up desk screen
monitorv2 {
    output = desc:Samsung Electric Company LC27RG50 H4ZN800083
    mode = 1920x1080@120
    position = 640x-2160
    scale = 1
    bitdepth = 10
    cm = hdr #hdredid
    vrr = 0 # 0 - off, 1 - on, 2 - fullscreen only
    supports_wide_color = 1
    supports_hdr = 1
    #sdrbrightness = 1.2
    #sdrsaturation = 0.98
    #sdr_min_luminance = 0.005
    #sdr_max_luminance = 160
    #min_luminance = 0.005
    #max_luminance = 400
}
#right desk screen
monitorv2 {
    output = desc:ViewSonic Corporation XG272-2K-OLED XJY241700095
    mode = 2560x1440@120
    position = 2560x-1600
    scale = 1
    transform = 1
    bitdepth = 10
    cm = hdr #hdredid
    vrr = 1 # 0 - off, 1 - on, 2 - fullscreen only
    supports_wide_color = 1
    supports_hdr = 1
    #sdrbrightness = 1.2
    #sdrsaturation = 0.98
    #sdr_min_luminance = 0.005
    #sdr_max_luminance = 160
    #min_luminance = 0.005
    #max_luminance = 400
}
# Laptopscreen
monitorv2 {
    output = desc:Thermotrex Corporation TL134ADXP01-0
    mode = 2560x1600@165.00Hz
    scale = 1
  #  bitdepth = 10
   # cm = hdr
  #  vrr = 0 # 0 - off, 1 - on, 2 - fullscreen only
  #  supports_wide_color = 1
  #  supports_hdr = 1
  #  sdrbrightness = 1.2
  #  sdrsaturation = 0.98
  #  sdr_min_luminance = 0.005
  #  sdr_max_luminance = 250
  #  min_luminance = 0.005
  #  max_luminance = 400
}

# Asus OLED
monitorv2 {
    output = desc:ASUSTek COMPUTER INC PG32UCDP SALMQS120128
    mode = 3840x2160@240
    position = auto-up
    scale = 1
    #bitdepth = 12
    cm = hdr #hdredid
    vrr = 2 # 0 - off, 1 - on, 2 - fullscreen only
    supports_wide_color = 1
    supports_hdr = 1
    #sdrbrightness = 1.2
    #sdrsaturation = 0.98
    #sdr_min_luminance = 0.005
    #sdr_max_luminance = 160
    #min_luminance = 0.005
    #max_luminance = 400
}

# GIGA-BYTE links schreibtisch
monitorv2 {
    output = desc:GIGA-BYTE TECHNOLOGY CO. LTD. GS27Q 23282B002014
    mode = 2560x1440@120.00Hz
    transform = 3
    position = -800x-1800
    scale = 1
    #bitdepth = 12
    cm = hdr #hdredid
    vrr = 2 # 0 - off, 1 - on, 2 - fullscreen only
    supports_wide_color = 1
    supports_hdr = 1
    #sdrbrightness = 1.2
    #sdrsaturation = 0.98
    #sdr_min_luminance = 0.005
    #sdr_max_luminance = 160
    #min_luminance = 0.005
    #max_luminance = 400
}

#monitor=desc:Valve Corporation Index HMD 0xE94D96F6,2880x1600@144.00Hz, 0x0, 1

monitor=,preferred,auto,1
