ecosystem {
    enforce_permissions = 1
}
# Permissions
 permission = ~/tools/grim-hyprland/build/grim, screencopy, allow
 permission = /usr/lib/xdg-desktop-portal-hyprland, screencopy, allow
 permission = /usr/libexec/xdg-desktop-portal-hyprland, screencopy, allow
 permission = /usr/lib64/xdg-desktop-portal-hyprland, screencopy, allow
 permission = /usr/bin/appsuite-.*, screencopy, allow
 permission = /usr/bin/grim, screencopy, allow
 permission = /usr/bin/hyprpicker, screencopy, allow
 permission = /usr/bin/hyprpm, plugin, ask
 permission = power-button, keyboard, allow
 permission = power-button-1, keyboard, allow
 permission = video-bus, keyboard, allow
 permission = video-bus-1, keyboard, allow
 permission = intel-hid-events, keyboard, allow
 permission = sleep-button, keyboard, allow
 permission = logitech-usb-receiver-keyboard, keyboard, allow
 permission = logitech-usb-receiver-keyboard-1, keyboard, allow
 permission = logitech-usb-receiver, keyboard, allow
 permission = asus-wmi-hotkeys, keyboard, allow
 permission = asustek-computer-inc.-n-keydevice-2, keyboard, allow
 permission = asustek-computer-inc.-n-keydevice, keyboard, allow
 permission = at-translated-set-2-keyboard, keyboard, allow
 permission = hl-virtual-keyboard-wtype, keyboard, allow
 permission = generic-usb-audio-consumer-control, keyboard, allow
 permission = logitech-usb-receiver-consumer-control, keyboard, allow
 permission = logitech-pro-x-wireless-gaming-headset-consumer-control, keyboard, allow
 permission = logitech-usb-receiver-system-control, keyboard, allow
 permission = burrbrown-from-texas-instruments-usb-audio--codec, keyboard, allow
 permission = generic-usb-audio, keyboard, allow
 permission = 3d-camera:-etronvideo, keyboard, allow
 permission = .*, keyboard, ask
