##################
# video settings #
##################

hwdec=auto
profile=high-quality
video-sync=display-resample
keep-open=no
force-window=immediate
fs=yes
# Disable the On Screen Controller (OSC).
osc=no

##################
# audio settings #
##################

volume=100
#audio-device=alsa/default
audio-pitch-correction=no
#audio-channels=auto
alang=en,de

##################
# other settings #
##################

# Pretend to be a web browser fix playback with some streaming sites
#user-agent="Mozilla/5.0"
cache=yes
demuxer-max-bytes=500M
demuxer-max-back-bytes=100M
cache-pause=no
cache-on-disk=no
cache-dir=~/.cache/

# subtitle language
#slang=en
#sub-codepage=cp1256
