context.modules = [
  {
    name = libpipewire-module-loopback
    args = {
      node.description = "PC Audio -> Default Sink"
      capture.props = {
        node.name           = "pc-audio-capture"
        audio.position      = [ FL FR ]
        target.object       = "pc-audio-sink"
        node.passive        = false
        node.dont-reconnect = false
      }
      playback.props = {
        node.name           = "pc-audio-playback"
        audio.position      = [ FL FR ]
        node.passive        = false
        node.dont-reconnect = false
      }
    }
  }
]
