monitor.alsa.rules = [
  {
    matches = [ { device.name = "~alsa_card.usb-Focusrite.*Scarlett_2i2.*" } ]
    actions = {
      update-props = {
        api.alsa.use-acp     = true
        device.profile       = "pro-audio"
        api.acp.auto-profile = false
        api.acp.auto-port    = false
      }
    }
  }
  {
    matches = [
          { node.name = "~alsa_input.usb-Focusrite.*Scarlett_2i2.*"  }
          { node.name = "~alsa_output.usb-Focusrite.*Scarlett_2i2.*" }
      ]
    actions = {
      update-props = {
        audio.format                    = "S32LE"
        api.alsa.period-size            = 128
        api.alsa.headroom               = 0
        node.latency                    = "128/48000" # 128 samples @ 48 kHz ~= 2.67 ms; 64/48000 is faster but less stable.
        session.suspend-timeout-seconds = 0
        node.pause-on-idle              = false
        api.alsa.htimestamp             = true
      }
    }
  }
]
