[preferred]
default=hyprland;gtk
org.freedesktop.impl.portal.FileChooser=termfilechooser

[filechooser]
env=TERMCMD=ghostty
cmd=$HOME/.config/xdg-desktop-portal/yazi-wrapper.sh
default_dir=$HOME
open_mode=suggested
save_mode=suggested
